spring.application.name=AOS_BE
server.port=${PORT:8080}
spring.datasource.url=jdbc:sqlserver://172.21.0.3:1433;databaseName=all_in_store
spring.datasource.username=sqlserver
spring.datasource.password=1234567as
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.security.oauth2.client.registration.google.client-id=1059527037272-8tcp2l0jfuefjia30ftr5h8ksjpat79k.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

spring.security.oauth2.client.registration.facebook.client-id=1165946465216566
spring.security.oauth2.client.registration.facebook.client-secret=04685dd41ebf68ae071987c7f5a2deca
spring.security.oauth2.client.registration.facebook.scope=email,public_profile

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=khannps39199@gmail.com
spring.mail.password=rrlf kvua odyp mliu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG
# --- Spring Core ---
#logging.level.org.springframework=DEBUG
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.data=DEBUG

# --- JPA and Hibernate ---
#logging.level.org.hibernate.SQL=DEBUG               # Show SQL queries
#logging.level.org.hibernate.type.descriptor.sql=TRACE  # Show SQL parameter values
#logging.level.org.hibernate.event.internal=DEBUG
#logging.level.org.hibernate.stat=DEBUG
#
## --- Spring Boot Autoconfiguration ---
#logging.level.org.springframework.boot.autoconfigure=DEBUG
#
## --- JDBC Connections (HikariCP) ---
#logging.level.com.zaxxer.hikari=DEBUG
#
## --- OAuth2 ---
#logging.level.org.springframework.security.oauth2=DEBUG
#logging.level.org.springframework.security.oauth2.client=DEBUG
#
## --- Validation ---
#logging.level.org.hibernate.validator=DEBUG
#
## --- General SQL Execution ---
#logging.level.jdbc.sqlonly=DEBUG
#logging.level.jdbc.sqltiming=DEBUG


jwt.secret=thisIsASecretKeyThatIsAtLeast32Bytes

