name: Build and Deploy to GitHub Pages (Alternative)

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: production

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Clean and install dependencies
        run: |
          cd AOS_FE/AOS_FE
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install
          npm install @rollup/rollup-linux-x64-gnu --save-dev

      - name: Build for Production
        run: |
          cd AOS_FE/AOS_FE
          NODE_ENV=production npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './AOS_FE/AOS_FE/dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4